on:
  - push
  - workflow_dispatch

permissions: write-all

name: 1. DEV Environment Build
jobs:
  build_and_deploy:
    name: Build and Deploy
    uses: p6m-dev/github-actions/.github/workflows/build-deploy-maven.yaml@main
    secrets:
      ARTIFACTORY_USERNAME: ${{'{'}}{ secrets.ARTIFACTORY_USERNAME }}
      ARTIFACTORY_IDENTITY_TOKEN: ${{'{'}}{ secrets.ARTIFACTORY_IDENTITY_TOKEN }}
      UPDATE_MANIFEST_TOKEN: ${{'{'}}{ secrets.UPDATE_MANIFEST_TOKEN }}
    with:
      ARTIFACTORY_HOSTNAME: ${{'{'}}{ vars.ARTIFACTORY_HOSTNAME }}