apiVersion: meta.p6m.dev/v1alpha1
kind: PlatformApplication
metadata:
  name: {{ artifact-id }}
  labels:
    p6m.dev/app: {{ artifact-id }}
spec:
  config:
    SERVER_PORT: "8080" # Service Port
    MANAGEMENT_SERVER_PORT: "8081" # Management Port
    LOGGING_STRUCTURED: "true"{% if persistence == 'CockroachDB' %}
    PERSISTENCE_DATABASE_URL: "$(crdb_{{ artifact_id }}_jdbc_connection_string)" {% endif %}{% if use-default-service == false %}{%- for service_key in services %}
{%- set service = services[service_key] %}
    CORE_SERVICES_{{ service['PROJECT_NAME'] }}_HOST: "{{ service['project-name'] }}.{{ service['project-name'] }}"
    CORE_SERVICES_{{ service['PROJECT_NAME'] }}_PORT: "8080"
{%- endfor %}{% endif %}
  resources: {% if persistence == 'CockroachDB' %}
    crdb:
      - name: {{ artifact-id }}{% else %}{}{% endif %}
  deployment:
    image: {{ artifact-id }}-server:latest
    ports:
      - protocol: {% if service-protocol == 'gRPC' %}grpc{% else %}http{% endif %}
        port: 8080
      - protocol: http
        port: 8081
    readinessProbe:
      port: 8081
      path: /health/readiness
